### PR TITLE
Allow Summary metrics to have null min or max values

### PR DESCRIPTION
**Pull request by kscaldef**
Not all metric sources provide both min and max values for all metrics which we might
want to map to Summaries.  This allows either of these fields to be null, which the
NewRelic data backend will interpret as a double NaN and treat appropriately.

### CODE REVIEW

**Comment by jkwatson** [comment]
This looks like a great change. Can you add some quick unit tests for these cases?

**Comment by jkwatson** [comment]
@kscaldef looks like unit tests are failing for this, as well

**Comment by kscaldef** [comment]
@jkwatson updated that test to reflect the change.

**Comment by jkwatson** [comment]
@kscaldef is there urgency on getting this change into an official release? If so, I'll go ahead and kick off the release process.

**Pull request merged**
